logging:
  level:
    org.springframework: DEBUG
    com.bytecubed: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %logger.%M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ./logs/teams.log

persistence:
  mongo:
    url: localhost
    port: 27017

management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health